[package]
name = "db-rs-derive"
version = "0.2.0"
edition = "2021"
description = "macros for db-rs"
license = "BSD-3-Clause"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.107"
quote = "1.0.23"
db-rs = "0.2.0"
